# Site settings
title: Lector David
name: Lector David
description: + notes + presentations +
baseurl: "" # the subpath of your site, e.g. /blog
url: https://lectorDavid.github.io
github_username: lectorDavid

# Build settings
markdown: kramdown
permalink: pretty
theme: minima
plugins:
  - jekyll-feed

exclude:
  - README.md
  - reveal.js/index.html
  - reveal.js/plugin/markdown/example.html
  - reveal.js/plugin/notes/notes.html
  - reveal.js/plugin/notes-server/notes.html
  - reveal.js/test/
  - reveal.js/*.md
  - reveal.js/Gruntfile.js
  - reveal.js/package.json
  - reveal.js/LICENSE